### ISSUE TITLE
incorrect padding type error

### ISSUE THREAD

**Issue by rbytheway** [BinaryDefense/auto-ossec#12]
receiving the following error when running auto_ossec.py on a linux system.
Traceback (most recent call last):
  File "./auto_ossec.py", line 373, in <module>
    data = base64.b64decode(data)
  File "/usr/lib64/python2.6/base64.py", line 76, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding
None

**Comment by rbytheway** [comment]
closing issue...ossec server broken causing null value to be decoded

**Comment by aborin** [comment]
Did you find a fix on the server side?  I am running into the same issue with my deployment.
