### ISSUE TITLE
"You can't export keys on an agent"

### ISSUE THREAD

**Issue by jerseyfoxcom** [BinaryDefense/auto-ossec#13]
Getting the following when I request a key from a Linux machine :-

[*] The auto enrollment OSSEC Server is now listening on 9654
('Client connected with ', ('xx.xx.xx.xx', 36542))
[*] Provisioned new key for hostname: ip-xx.xx.xx.xx with IP of: xx.xx.xx.xx
[*] Sending new key to ip-xx.xx.xx.xx:2016/11/24 16:49:37 manage_agents: You can't export keys on an agent
Pairing complete. Terminating connection to client.
[*] New OSSEC agent added - triggering restart of service to add..

Any ideas why this is happening?

**Comment by jerseyfoxcom** [comment]
On the other side I see this :-

[*] Pulled hostname and IP, encrypted data, and now sending to server.
[*] We received our new pairing key for OSSEC, closing server connection.
[*] Something did not complete. Does this system have Internet access?
Traceback (most recent call last):
  File "auto_ossec.py", line 343, in <module>
NameError: name 'path' is not defined
None

**Comment by jerseyfoxcom** [comment]
[*] Connected to auto enrollment server at IP: 172.31.20.56
[*] Pulled hostname and IP, encrypted data, and now sending to server.
[*] We received our new pairing key for OSSEC, closing server connection.
[*] Removing any old keys.
[*] Something did not complete. Does this system have Internet access?
Traceback (most recent call last):
  File "auto_ossec.py", line 356, in <module>
  File "base64.py", line 78, in b64decode
**TypeError: Incorrect padding**

**Comment by ghost** [comment]
I have a related issue, except that my key exchange appears successful apart from the Base64 padding error. I am using the virtual appliance provided by OSSEC.

**Server:**
Client connected with  (<server IP>)
004
004
004
[*] Provisioned new key <etc>
[*] Sending new key to <hostname>: 0
Pairing complete. Terminating connection to client.
[*] New OSSEC agent added - triggering restart of service to add..

**Client**
[*] Connected to auto enrollment server at IP: <server IP>
[*] Pulled hostname and IP, encrypted data, and now sending to server.
[*] We received our new pairing key for OSSEC, closing server connection.
[*] Removing any old keys.
[*] Something did not complete. Does this system have Internet access?
Traceback (most recent call last):
  File "auto_ossec.py", line 356, in <module>
  File "base64.py", line 78, in b64decode
TypeError: Incorrect padding
None

**Comment by jerseyfoxcom** [comment]
Yeah - First issue was permissions related it seems. I'm now getting only the "incorrect padding" with base64 encoding, same as yourself.

**Comment by enggbilalmalik** [comment]
any luck with this issue?

**Comment by jerseyfoxcom** [comment]
I ended up writing my own key exchanger!

**Comment by enggbilalmalik** [comment]
hmm, have you shared it anywhere please? and does it work for mass deployments?

**Comment by b1tfox** [comment]
I´m also interested in a working solution for keyexchange.

**Comment by trustedsec** [comment]
I'll be pushing an update for this  in a moment- it was due to not waiting for manage_agents to complete when using pexpect.spawn.
