### ISSUE TITLE
32 bit windows 7

### ISSUE THREAD

**Issue by asarratore** [BinaryDefense/auto-ossec#14]
I saw in another issue that there is no support for 32 bit.  Are there any other suggestions for auto deploying to 32 bit workstations.  Most of my fleet are 32 bit still.  We did get this working for our 64 bit workstations though, so that is great, and going forward it is great, but for the present, we are kind of back to square one.

**Comment by kitaro97** [comment]
I'm in the same boat.   Any chance of getting the source?  Willing to spend some time with it to try getting a 32-bit build together...

**Comment by simpsonlang** [comment]
I also have this issue. We have a couple 2008 (non-R2) servers which are 32 bit and if I had the source I could compile it 32 bit. Another option I'm considering is maybe trying to get the python script to run under windows if I can figure out how to portablize python.

**Comment by kitaro97** [comment]
Downloaded auto-ossec.py.   I'm adding the Python extension to Visual Studio to see if I can get this rolling

**Comment by trustedsec** [comment]
I've recompiled this to a 32 binary now, should work with all versions.
