### ISSUE TITLE
Does this tool support re-enrollment?

### ISSUE THREAD

**Issue by plastikman** [BinaryDefense/auto-ossec#15]
With tools like ossec-authd you can automatically register agents to the ossec server but there is no way to see if a host is already registered.  Does this tool support re-registering hosts with the same key/name/ip?

**Comment by plastikman** [comment]
Looking through the code it seems that this does support re-enrollment. 

One question, with the re-enrollment it seems it it looking for the host name, what if the host name changes? 

line 99 - 115 in auto_server.py It seems that this should also verify the IP address.

**Comment by trustedsec** [comment]
if the hostname changes you would need to rerun autoossec
