### ISSUE TITLE
re-register and hostid

### ISSUE THREAD

**Issue by b1tfox** [BinaryDefense/auto-ossec#16]
Hi.

I have a few issues so far.
Running first time registering a Windows machine goes great, server adds it and starts to log.
The client "might" need to get reinstalled for different reasons and running auto_ossec.exe again gives me error.
Same Hostname and IP will not be accepted so I have to manually remove old entry in server, that is not ok since we need the history. It would append to the old host.

The network is restricted from using static ip in any code/script, so we need to add hostid when running auto_ossec.exe. Since the client doesn't allow hostid, the script has to resolve the hostid parameter before running script.

I would also like to be able to change aes key in server and windows binary

/Thanks

**Comment by trustedsec** [comment]
You can recompile the AES key with auto_client.py, download PyInstaller and Python and compile on a Windows machine.

python pyinstaller.py --onefile auto_client.py. The .exe is only there as a conceptual working exe to make it easy. No plans on being able to add AES key via command line.

For the dynamic vs static IP addresses, you can specify a second argument of '0.0.0.0/0' which would assign a non-static IP address to the hostname and can rotate and move.
