### ISSUE TITLE
auto_server.py times out if /etc/client.keys has large number of entries

### ISSUE THREAD

**Issue by simpsonlang** [BinaryDefense/auto-ossec#19]
If I manually open manage_agents and add an agent I see the CPU jumps to 100% and it takes anywhere from 20-60 seconds to add a new agent. This is due to having 1,417 entries in my client.keys. Sometimes when the delay is too large auto_server.py will timeout though it says the key was created ok. I've managed to work around it by adding a virtual CPU to soak up the load however at some point to number of entries will grow to the point where it will happen again. I was wondering if their is a way to adjust the script to increase the timeout when it's waiting for manage_agents to respond?

**Comment by simpsonlang** [comment]
I noticed in the output when it times out I see a timeout: 30. So I think if I add child.timeout=300  above the child.expect line then that should solve it.

**Comment by trustedsec** [comment]
Thanks, I've added this to the latest codebase.
