### ISSUE TITLE
32-Bit Compatibility Issue - Windows 64-Bit

### ISSUE THREAD

**Issue by stephenh1991** [BinaryDefense/auto-ossec#2]
I can't run the .exe on a 64-bit windows server.

Is this a known bug?

**Comment by stephenh1991** [comment]
Hi,

Is there any chance you could let me know if this is a known problem?

Thanks,
Steve

**Comment by trustedsec** [comment]
Works fine on a 64 bit operating system - all testing was done on a 64-bit we don't support 32 bit..

**Comment by stephenh1991** [comment]
Hi,

Thanks for the reply on this, I get this error when I run the .exe from an
admin run prompt:

[image: Inline image 1]

Any ideas?

Thanks,
Steve

**Comment by trustedsec** [comment]
Not really sure - I just tested on a Windows 7, Windows 8.1, Windows 10, and Server 2012 R2 with auto-ossec.exe all 64 bit and works fine. You need to ensure that your deploying both the auto ossec server onto a machine that is running OSSEC so that it can provision the key appropriately. I also can't see the image attached, can you pastebin the output?

**Comment by stephenh1991** [comment]
Yeah, definitely a strange one!

The output basically says:

Unsupported 16-bit application

Cannot start or run due to an incompatibility with 64-bit versions of
windows. Please contact your software provider to obtain a 64-bit version
of the application.

Thanks,
Steve

**Comment by stephenh1991** [comment]
Out of interest, are you just running the .exe standalone? If so can you
send me the one you are testing with?

**Comment by stephenh1991** [comment]
Hi,

The issue is resolved for me now I re-downloaded the zip archive from
github and all is well... I must have just gotten unlucky and the archive
got corrupt in some way.

Thanks again for your help and sorry for the inconvenience!
Steve
