### ISSUE TITLE
agent not being registered in server 

### ISSUE THREAD

**Issue by ilfox** [BinaryDefense/auto-ossec#20]
Hi I am using ossec server 2.8.3 on a centos 7.3 machine and client side a Windows 2012 R2 machine with ossec agent 2.9.2. When running auto-ossec <server_ip>, I get the following output;

Python version 3.5

Client side:
[*] Connected to auto enrollment server at IP: 10.18.119.14
[*] Pulled hostname and IP, encrypted data, and now sending to server.
[*] We received our new pairing key for OSSEC, closing server connection.
[*] Removing any old keys.
[*] Successfully imported the new pairing key.
[*] Stopping the OSSEC service, just in case its running.
[*] Overwriting the ossec.conf to incorporate server host IP address.
[*] Finished. Started the OSSEC service. Auto Enrollment for OSSEC is now finish

Server side:
Client connected with  ('10.18.139.101', 58745)
new() missing 1 required positional argument: 'mode'
Traceback (most recent call last):
  File "auto_server.py", line 164, in handle
    data = aescall(secret, data, "decrypt")
  File "auto_server.py", line 145, in aescall
    cipher = AES.new(secret)
TypeError: new() missing 1 required positional argument: 'mode'
Pairing complete. Terminating connection to client.

But the agent is not being registered and hence no key can be retrieved and added to the agent config. Can you please help?

**Comment by trustedsec** [comment]
Won't be able to look at this for a bit to dive into it, you can try assigning a variable to server:

Replace "cipher = AES.new(secret)"

with:

obj = AES()
cipher = obj.key(secret)

**Comment by trustedsec** [comment]
Ah thats probably not it - use the same length for the key that was in their due to length of the encryption in bytes. I'm guessing you changed the secret key (good thing btw). Needs to be the same length:

secret = "(3j+-sa!333hNA2u3h@*!~h~2&^lk<!B"

Needs to be 32 bytes in length. That's what padding is for, but it's not implemented in this.

**Comment by ilfox** [comment]
To be honest I didn't change the key.

**Comment by trustedsec** [comment]
Then not sure to be honest, I'll have to debug but I won't have time for a little while.

**Comment by trustedsec** [comment]
Python3 would be recommended.

**Comment by trustedsec** [comment]
I'm not able to reproduce this unfortunately, I tried this with both python2, and python3 with a server and client (windows 10). Pairs appropriately, these were base install Ubuntu and Windows 10. 

What OS are you using for the server?

**Comment by ilfox** [comment]
Centos 6.8 and I have agents both with centos 6.8 and Windows server 2012
R2. With the agent being centos 6.8 I had an issue with the glibc version
because the minimum requirement is 2.14

**Comment by trustedsec** [comment]
I've just released a new version 1.7 which fixes a padding issue, give it a shot but I can't for the life of me reproduce this one...

**Comment by trustedsec** [comment]
You are running the server side on CentOS?

**Comment by trustedsec** [comment]
For server side, try running python -m install pycrypto and running again, you might be using pycryptodome on mistake...

**Comment by ilfox** [comment]
After downloading the latest version of auto-ossec, I ran auto_server.bin
with python 2 and the windows agent got automatically registered :). The
only issue remaining is the linux agent running on CentOS 6.8 (glib version
2.12) because I get the following error;

[root@testvm]# ./auto_ossec.bin X.X.X.X
./auto_ossec.bin: /lib64/libc.so.6: version `GLIBC_2.14' not found
(required by /tmp/_MEIMSOuNY/libz.so.1)

**Comment by ilfox** [comment]
In fact I just tried it with an agent running CentOS 7.3 and it worked.

**Comment by trustedsec** [comment]
Hey, starting to make some progress here. Let me check on the others.

**Comment by trustedsec** [comment]
Have you tried sudo yum update glibc on the CentOS 6.8?

**Comment by trustedsec** [comment]
Saw a tutorial here:

mkdir ~/glibc_install; cd ~/glibc_install 

wget http://ftp.gnu.org/gnu/glibc/glibc-2.14.tar.gz

tar zxvf glibc-2.14.tar.gz

cd glibc-2.14

mkdir build

cd build

../configure --prefix=/opt/glibc-2.14

make -j4

sudo make install

export LD_LIBRARY_PATH=/opt/glibc-2.14/lib

**Comment by trustedsec** [comment]
Or:

tar zxvf glibc-2.14.tar.gz
cd glibc-2.14
mkdir build
cd build
../configure --prefix=/opt/glibc-2.14
make -j4
make install

**Comment by trustedsec** [comment]
Looks like a compatibility issue when compiling on newer OS's:

https://stackoverflow.com/questions/17654363/pyinstaller-glibc-2-15-not-found

I don't see this as a auto_ossec but, need to update to the latest GLIBC if possible would be my recommendation on that front.
