### ISSUE TITLE
server script fails taking ossec down

### ISSUE THREAD

**Issue by LFBernardo** [BinaryDefense/auto-ossec#4]
Hi,

I run the script permanently with a scheduled restart of the script and OSSEC at 6AM every morning (not the vm just the services)

I have now found this in my logs for every restart instance. Any help would be appreciated.

SERVICE RESTART COMPLETE
Sun May  8 06:00:05 SAST 2016

[*] The auto enrollment OSSEC Server is now listening on 9654
Traceback (most recent call last):
  File "/var/ossec/bin/new_auto_ossec", line 171, in <module>
    t = ThreadedTCPServer(('',9654), service)
  File "/usr/lib64/python2.6/SocketServer.py", line 412, in **init**
    self.server_bind()
  File "/usr/lib64/python2.6/SocketServer.py", line 423, in server_bind
    self.socket.bind(self.server_address)
  File "<string>", line 1, in bind
socket.error: [Errno 98] Address already in use

Seems it is not happy with the  command " t = ThreadedTCPServer(('',9654), service)"

**Comment by branchnetconsulting** [comment]
I've seen something like this, too.  It seems that after stopping this script, the socket lingers for a while.   I recommend you stop the service, pause for 30 seconds, and then start it.  That seems to be long enough for the old socket to close down.

**Comment by trustedsec** [comment]
I've pushed a new version - this should allow reuse. Thanks for reporting.
