### ISSUE TITLE
Option to use wildcard IP addresses

### ISSUE THREAD

**Issue by bkcarter333** [BinaryDefense/auto-ossec#5]
Due to DHCP settings and many machines being powered on and off at different times in a retail world, we have opted to use the wildcard setting for IP addresses in the OSSEC key file. Is there any way to tell the auto_server.py script to ignore the actual address and insert a wildcard? 

I have done some Python coding, but not enough to know exactly how to do this. If you could give me some pointers as to what I could change it would be great!  

Thanks
Bryan Carter

**Comment by LFBernardo** [comment]
Maybe try modifying  self.client_address[0] to contain the wildcards in the
line "ipaddr = self.client_address[0]"

**Comment by trustedsec** [comment]
I'll have this added shortly

**Comment by trustedsec** [comment]
Give it a shot - I just pushed the latest up there - when using auto_ossec.exe or auto_ossec.bin do:

auto_ossec.exe 192.168.5.5(serverIP) *

This should now allow \* for the ipaddr instead.
