### ISSUE TITLE
Something Did Not Complete: Name 'path' is not defined

### ISSUE THREAD

**Issue by Theory5** [BinaryDefense/auto-ossec#6]
Hello,

so I THINK I setup auto_ossec correctly. I have a windows 10 system, and the OSSEC appliance on a VM. But when I run the auto_ossec.exe file on my windows system, it grabs the key then claims something didn't complete. Then it prints "name 'path' is not defined".

Any help? Also, on my server I put auto_ossec.py into chkconfig in /etc/init.d/ is this correct? When I invoke service auto-ossec (no matter the flag after) It prints this:

 service auto-ossec status
[*] The auto enrollment OSSEC Server is now listening on 9654
Traceback (most recent call last):
  File "/etc/init.d/auto-ossec", line 176, in <module>
    t = ThreadedTCPServer(('',9654), service)
  File "/usr/lib64/python2.6/SocketServer.py", line 412, in **init**
    self.server_bind()
  File "/usr/lib64/python2.6/SocketServer.py", line 423, in server_bind
    self.socket.bind(self.server_address)
  File "<string>", line 1, in bind
socket.error: [Errno 98] Address already in use

Which I take to mean the auto-ossec part of it is running? Ossec is running too, but it doesn't update anything.

Any help is appreciated. I know I did something wrong, but I'm pulling my hair out trying to figure out what!

**Comment by branchnetconsulting** [comment]
To help us help you, please try running auto_ossec.exe on your Windows 10 system again and then capture and send us the full text output of the process on both your Windows 10 system and on the server where you are running auto_server.py.

Did you already install OSSEC itself on your Windows 10 system before trying to run auto_ossec.exe?  That is required.  Also, did you install OSSEC to the default location of "C:\Program Files (x86)\ossec-agent".  That is also required for auto_ossec.exe to work.

Kevin

**Comment by Theory5** [comment]
Wait, the documentation didn't seem to say anything about requiring the original OSSEC agent... No wonder it can't find a path! Let me try this. Thanks! Could this be made clearer in the documentation?

**Comment by Theory5** [comment]
It works! Still don't know why I get those errors on the server when I Run 'service ossec status' but that's another less pressing issue. Thanks again!

**Comment by branchnetconsulting** [comment]
I'm glad you are working now.  You are welcome for the assistance.

About your other issue, you really can't just put auto_ossec.py or auto_server.py into /etc/init.d/.  These  are not service control scripts. This is why it errors out on you when you try to check status.  

You don't want auto_ossec.py to be a service.  For a given agent system you are only running it once anyway.  

You may well want auto_server.py to run as a service.  The author actually recommends running it under supervisord.  I have started writing up the process of installing supervisord and setting it up to manage auto_server.py.  I'd be happy to share it when it's done.
