### ISSUE TITLE
Auto restart of OSSEC server service upon agent registration appears to be broken

### ISSUE THREAD

**Issue by branchnetconsulting** [BinaryDefense/auto-ossec#7]
Procedure ossec_monitor() in auto_server.py appears intended to check every 5 minutes to see if any auto-registrations have occurred and if so to restart the OSSEC server services.  What appears to actually happen is the 5 minute timer is started when auto_server.py is first run, and at the end of 5 minutes it does a one-time check for the auto-registration flag file and restarts OSSEC if the flag file is there.  It never checks again after that.  I put a "while true" loop around the contents of ossec_monitor() and then it kept on checking every 5 minutes, but it had a maddening side-effect of the tcp/9654 socket getting handed off to the OSSEC analysisd daemon upon stopping auto_server.py, making auto_server.py unable to start until OSSEC was restarted first.  I ended up using a cron job to do the work of ossec_monitor independently from auto_server.py.

**Comment by trustedsec** [comment]
Thanks for the bug report! Just released 1.5 which has a lot of new features and updates. Incorporated it into this one.
