### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by branchnetconsulting** [BinaryDefense/auto-ossec#8]
You might want to consider adding support for Mac OSSEC agents.  I found I was able to get this to work by making auto-ossec.py treat a Mac just like you treat Linux OSSEC agents.  That, plus use "/var/ossec/bin/ossec-control stop/start" to control the OSSEC agent service rather than "service ossec stop/start".  That works for both Mac and Linux platforms.  I've only tested Mac support with a Mac running El Capitan.  You can see how I did it here:

https://github.com/branchnetconsulting/auto-ossec/blob/master/auto_ossec.py

By the way, at least with Mac OS "El Capitan", I was pleased to find that the OSSEC agent installs from tarball very cleanly now.  You just need pycrypto and Xcode installed.  Older versions of Mac OS and OSSEC required special tweaks to get OSSEC agent running on a Mac.  The only extra step I had to take was this one to make OSSEC agent start at boot time.

https://wikis.utexas.edu/display/ISO/Configuring+OSSEC+HIDS+on+OS+X+Yosemite#ConfiguringOSSECHIDSonOSXYosemite-Automaticallylaunchatsystemboot

Thanks for your great work on this,
Kevin

**Comment by trustedsec** [comment]
Much appreciated Kevin! I've added OSX support to the latest version.
